### ISSUE TITLE
update node-sql-parser 4.8.0

### ISSUE THREAD

**Issue by araera111** [araera111/mysql-to-zod#13]
tomorrow or ... day after tomorrow

**Comment by araera111** [comment]
updated

**Comment by TonyGravagno** [comment]
It looks like the pnpm-lock.yaml was updated with v4.8.0, but package.json in main branch still has v4.7.0. Therefore, npm install from a git clone still uses the old version.

However, updating to 4.8.0 does not resolve issue #5 .
Please re-open this issue so that you can re-apply the update on the dependency. But there is no need to update yet - you may want to wait until there is another update to node-sql-parser.

**Comment by araera111** [comment]
sorry

**Comment by araera111** [comment]
updated
