### ISSUE TITLE
dev v2.2.5 : globalSchema.ts has redundant EOL

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#169]
Trivial issue after recent dev changes.  
Note that extra "\n" (EOL) characters aren't removed from globalSchema constant. They were before recent changes.

![image](https://github.com/user-attachments/assets/495ed481-c7fa-4c3b-b27d-015aec862b0d)

**Comment by araera111** [comment]
The fix has been merged due to #176. We have changed the method for retrieving key-value pairs, opting to count the number of tabs instead of performing multiple line breaks. If this approach still causes issues, we may need to handle TypeScript's AST more thoroughly. For now, it seems to be handling the cases you submitted without any problems.

**Comment by araera111** [comment]
If you encounter any errors again, please feel free to reopen the issue.
