### ISSUE TITLE
Remove redundant lint script from package.json?

### ISSUE THREAD

**Issue by TonyGravagno** [araera111/mysql-to-zod#186]
The code package.json file includes these scripts:

```json
  "lint": "pnpm biome check --apply ./src",
  "fmt": "pnpm biome format --write ./src",
  "check": "pnpm biome check --write ./src",
```

Since the --apply function is no longer valid, I suggest removing the '--lint' script line.

Assign to me if approved.

**Comment by araera111** [comment]
Thank you for pointing that out. I really appreciate your attention to detail, as it's something I'm not always the best at. I considered assigning this to you, but since it's an issue I originally created, I went ahead and cleaned it up myself. My mother has been telling me since I was a child: 'If you make a mess, clean it up!' Recently, my wife has also started saying the same thing.
